### ISSUE TITLE
Support for file (open/save) dialogs?

### ISSUE THREAD

**Issue by amwmedia** [tomas/dialog#15]
Do you think it would be difficult to add support for standard file save/open dialogs?

**Comment by tomas** [comment]
Not really. At least zenity supports a `--file-selection` argument. Not sure about macOS or Windows, though.

**Comment by amwmedia** [comment]
I ended up finding [dialog-node](https://www.npmjs.com/package/dialog-node) which does appear to support the functionality I was looking for.
