### ISSUE TITLE
Compilation error @ 5:19 in VBS script

### ISSUE THREAD

**Issue by rgavrilov** [tomas/dialog#7]
it complains about this line `retValue = MsgBox messageText, messageType, messageTitle`
adding parenthesis around arguments to the `MsgBox` call fixes it.
Why did this start to happen?

Actual error message (ran using `cscript` from command line):

`c:\temp\proj\node_modules\dialog\msgbox.vbs(5, 19) Microsoft VBScript compilation error: Expected end of statement`

**Comment by NiklasGollenstede** [comment]
I get the same error on Windows 10 and the same fix makes it work.
The MSDN example also uses parenthesis for the call, **if they use the return value** (The language design of VBScript is simply amazing ...):
https://msdn.microsoft.com/en-us/library/sfw6660x(v=vs.84).aspx#Remarks

It would be very nice to have this fixed soon. I could submit a one-line PR if that helps.

**Comment by tomas** [comment]
This was fixed a [long time ago](4c8bc542). Sorry for the long delay!
