### ISSUE TITLE
Quotes in the message in windows

### ISSUE THREAD

**Issue by NiklasGollenstede** [tomas/dialog#8]
Having a `"` in the message causes the `.vbs` script to throw. Here is a simple demo:
`node -e "(function test() { console.log('running\n', test.toString(), '\n'); require('dialog').info('\"message', 'title', function(code, out, err) { if (err) console.log('Error:', err); }); })()"`
Removing the `\"` fixes the problem.
As a general countermeasure, I'd suggest to use `.replace(/"/g, "''")` (replace double quotes with two single quotes) for all stings passed to the VBScript in windows.

**Comment by tomas** [comment]
Yikes, good catch. I'll fix this right now.

**Comment by FireController1847** [comment]
right now. > *Days, months, then years pass...*

**Comment by NiklasGollenstede** [comment]
It is already in the code: fb42ebefa94aacad049c2f35e7a948806031abe4

I would have used two single quotes for every double quote, though. `.replace(/"/g, "''")`, as they are rendered the same.
